spring:
  profiles:
    active: dev
  jackson:
    date-format: dd-MM-yyyy
    time-zone: Europe/Warsaw
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: pass
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update