spring:
  profiles:
    active: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_EMAIL}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: pass
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update